describe('PRUEBA DOUBLE V PARTNERS', () => {
  it('Prueba 01 - Visita pagina WING', () => {
    cy.visit('https://www.wingo.com/')
    cy.contains('VUELO').click({force: true})
    cy.get('#linkIbe').click({force: true})
    cy.get('#btnIdaVuelta > span').click({force: true})
    cy.get('.input-origen > .select-drop > .info-airport > .select > .styledSelect').click({force: true})
    cy.get('[data-cod="BOG"]').should('be.visible').click({multiple: true})
    cy.get('.input-destino > .select-drop > .info-airport > .select > .styledSelect').click({force: true})
    cy.get('#comboDestino > [data-cod="CLO"]').click({force: true})
    cy.get('#selectPasj > .info-airport > .icon-chev').click({force: true})
    cy.get(':nth-child(1) > .bts-add > .plus').click({force: true})
    cy.get('.styledSelectMoneda').click({force: true})
    cy.get('#currencies > :nth-child(2)').click({force: true})
    cy.get('#fromDate > .icon-chev').click({force: true})
    cy.get('#inputOutboundDate > .cont-calendar > .cont-months > .date-picker-wrapper > :nth-child(1) > :nth-child(1) > .month-wrapper > .month1 > tbody > :nth-child(2) > :nth-child(4) > .day').click({force: true})
    cy.get('#date-window-container > .date-picker-wrapper > :nth-child(1) > :nth-child(1) > .month-wrapper > .month2 > tbody > :nth-child(2) > :nth-child(7) > .day').click({force: true})
    cy.get('.btn-search').click({force: true})
    cy.visit('https://booking.wingo.com/es/search/BOG/CLO/2023-03-09/2023-04-09/2/0/0/0/COP/0/0')
  })
})